apiVersion: v1
data:
  GITLAB_OMNIBUS_CONFIG: ZXh0ZXJuYWxfdXJsICdodHRwOi8vZ2l0bGFiJwpyZWdpc3RyeV9leHRlcm5hbF91cmwgJ2h0dHA6Ly9naXRsYWI6NDU2NycKcG9zdGdyZXNxbFsnZW5hYmxlJ10gPSB0cnVlCmdpdGxhYl9yYWlsc1snaW5pdGlhbF9zaGFyZWRfcnVubmVyc19yZWdpc3RyYXRpb25fdG9rZW4nXSA9ICJZclBQUjZUVVV2M0F6UmpBS0xpQiIKZ2l0bGFiX3JhaWxzWydpbml0aWFsX3Jvb3RfcGFzc3dvcmQnXSA9ICJVdE0tNW92LTJ1bS01SG8i
  REGISTRATION_TOKEN: WXJQUFI2VFVVdjNBelJqQUtMaUIK
kind: Secret
metadata:
  name: gitlab-secret
  namespace: gitlab
type: Opaque
